 
dist: trusty
sudo: required
language: cpp

branches:
  only:
  - master
  - dev

install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  
  - sudo apt-get -y install g++-7
  - sudo ln -f -s /usr/bin/g++-7 /usr/bin/g++
  - sudo apt-get -y install cmake
  - sudo apt-get -y install liblua5.1-0-dev
  - sudo apt-get -y install libeigen3-dev
  - sudo apt-get -y install libglm-dev
  - sudo apt-get -y install libgl1-mesa-dev
  - git clone https://github.com/planeworld/libnoise2d.git
  - mkdir buildlibnoise
  - cd buildlibnoise
  - cmake -DCMAKE_BUILD_TYPE=Release ../libnoise2d
  - make -j8
  - sudo make -j8 install
  - cd ..
  - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz
  - tar xf SFML-2.4.2-linux-gcc-64-bit.tar.gz
  - sudo mv SFML-2.4.2/lib/libsfml-* /usr/lib/
  - sudo mv SFML-2.4.2/include/SFML /usr/include/
  - sudo chmod -R go+rx /usr/include/SFML
  

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make -j8
  - sudo make -j8 install

