#!/bin/bash

PKGDIR=$(cd $(dirname $BASH_ARGV) 2>/dev/null && pwd)
export PATH=$PKGDIR/bin:/usr/bin/:$PATH
export LD_LIBRARY_PATH=$PKGDIR/lib/otb:$PKGDIR/lib:/usr/X11R6/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=$PKGDIR/lib:/usr/X11R6/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$PKGDIR/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$PKGDIR/include:$CPLUS_INCLUDE_PATH

