#!/usr/bin/env node

var ephemeris = require("./lib/ephemeris_jpl")
var convert = require("./lib/convert.js");

ephemeris.get("earth", "2014-05-13", function(err, res){
    var data = convert.ephemeris2vector(res.ephemeris);
    console.log(data);
});



